// YouTube data via Apify streamers/youtube-scraper (no OAuth needed)
// Confirmed field names from live run: viewCount, likes, commentsCount, date, thumbnailUrl, id, url
const APIFY_TOKEN    = process.env.APIFY_API_TOKEN
const YT_CHANNEL_URL = process.env.YT_CHANNEL_URL  // e.g. https://www.youtube.com/@handle
const ACTOR_ID = 'streamers~youtube-scraper'

export interface YTPost {
  platform: 'youtube'
  post_id: string
  title: string | null
  caption: string | null
  thumbnail_url: string | null
  permalink: string | null
  published_at: string
  views: number
  likes: number
  comments: number
  shares: number
  saves: number
  reach: number
  impressions: number
  engagement_rate: number
  watch_time_mins: number
}

export interface YTProfile {
  followers: number
  post_count: number
}

async function runApifyActor(input: Record<string, unknown>): Promise<unknown[]> {
  const url = `https://api.apify.com/v2/acts/${ACTOR_ID}/run-sync-get-dataset-items?token=${APIFY_TOKEN}&timeout=120&memory=1024`
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  })
  if (!res.ok) throw new Error(`Apify YT error ${res.status}: ${await res.text()}`)
  return res.json()
}

export async function fetchYTProfile(): Promise<YTProfile> {
  return { followers: 0, post_count: 0 }
}

export async function fetchYTPosts(): Promise<YTPost[]> {
  if (!APIFY_TOKEN || !YT_CHANNEL_URL) return []

  const items = await runApifyActor({
    startUrls: [{ url: YT_CHANNEL_URL }],
    maxResults: 25,
    maxResultsShorts: 0,
    maxResultsStreams: 0,
    downloadSubtitles: false,
    preferAutoGeneratedSubtitles: false,
  }) as Record<string, unknown>[]

  return items
    .filter(item => (item.url || item.id) && !item.error)
    .map(item => {
      // Confirmed field names from live Apify run
      const views    = Number(item.viewCount    ?? item.views    ?? 0)
      const likes    = Number(item.likes        ?? item.likeCount ?? 0)   // actor uses "likes"
      const comments = Number(item.commentsCount ?? item.commentCount ?? 0) // actor uses "commentsCount"
      const engagement_rate = views > 0 ? ((likes + comments) / views) * 100 : 0

      const videoId = String(item.id ?? '').replace(/^yt_/, '')
      const permalink = String(item.url ?? (videoId ? `https://www.youtube.com/watch?v=${videoId}` : ''))

      // Actor uses "date" field (confirmed from live data)
      const published_at =
        (item.date        as string) ??
        (item.uploadDate  as string) ??
        (item.publishedAt as string) ??
        new Date().toISOString()

      // Profile data embedded in first item
      const subscribers = Number(item.numberOfSubscribers ?? 0)
      const totalVideos  = Number(item.channelTotalVideos  ?? 0)
      void subscribers; void totalVideos // used in fetchYTProfile if needed

      return {
        platform: 'youtube' as const,
        post_id: `yt_${videoId || Math.random()}`,
        title: String(item.title ?? '').slice(0, 200) || null,
        caption: String(item.text ?? item.description ?? '').slice(0, 500) || null,
        thumbnail_url: String(item.thumbnailUrl ?? item.thumbnail ?? '') || null,
        permalink: permalink || null,
        published_at: new Date(published_at).toISOString(),
        views, likes, comments,
        shares: 0, saves: 0,
        reach: views,
        impressions: views,
        engagement_rate: Math.round(engagement_rate * 100) / 100,
        watch_time_mins: Number(item.duration ?? 0) / 60,
      }
    })
}
